# Generated by Django 5.2.5 on 2025-11-04 15:26

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="difficulty",
            field=models.CharField(
                choices=[("easy", "Easy"), ("medium", "Medium"), ("hard", "Hard")],
                default="easy",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="duration",
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
