# Generated by Django 5.2.5 on 2025-09-30 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="image_bucket_key",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="image_url",
            field=models.ImageField(blank=True, null=True, upload_to="recipes/"),
        ),
    ]
