# Generated by Django 5.2.5 on 2025-11-21 16:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_recipe_difficulty_recipe_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="steps",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(blank=True, null=True),
                blank=True,
                null=True,
                size=None,
            ),
        ),
    ]
