# Generated by Django 5.2.5 on 2025-09-27 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "recipes",
            "0002_alter_recipe_options_recipe_created_at_recipe_owner_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="imageUrl",
            field=models.ImageField(null=True, upload_to="recipes/"),
        ),
    ]
