# Generated by Django 5.2.5 on 2025-09-30 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_recipe_image_bucket_key_alter_recipe_image_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="image_url",
        ),
    ]
